// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5wdzqYAVklJxdFBZ_ghKeM8PogSSPW4c',
    appId: '1:360652246632:web:5b49906f3d205b733c35dd',
    messagingSenderId: '360652246632',
    projectId: 'my-portfolio-42ccf',
    authDomain: 'my-portfolio-42ccf.firebaseapp.com',
    storageBucket: 'my-portfolio-42ccf.firebasestorage.app',
    measurementId: 'G-JRJ2PXTXES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzgJ0GUczmOyw6ih6j1nJ25fLefBsKQO4',
    appId: '1:360652246632:android:6d1ba490a276df6f3c35dd',
    messagingSenderId: '360652246632',
    projectId: 'my-portfolio-42ccf',
    storageBucket: 'my-portfolio-42ccf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcGPIz1hnBOJU-P-lNy6h6A4j3_ALWMyc',
    appId: '1:360652246632:ios:fff4c23e241454ad3c35dd',
    messagingSenderId: '360652246632',
    projectId: 'my-portfolio-42ccf',
    storageBucket: 'my-portfolio-42ccf.firebasestorage.app',
    iosBundleId: 'com.example.newPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcGPIz1hnBOJU-P-lNy6h6A4j3_ALWMyc',
    appId: '1:360652246632:ios:fff4c23e241454ad3c35dd',
    messagingSenderId: '360652246632',
    projectId: 'my-portfolio-42ccf',
    storageBucket: 'my-portfolio-42ccf.firebasestorage.app',
    iosBundleId: 'com.example.newPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5wdzqYAVklJxdFBZ_ghKeM8PogSSPW4c',
    appId: '1:360652246632:web:80e1b84e11a37d123c35dd',
    messagingSenderId: '360652246632',
    projectId: 'my-portfolio-42ccf',
    authDomain: 'my-portfolio-42ccf.firebaseapp.com',
    storageBucket: 'my-portfolio-42ccf.firebasestorage.app',
    measurementId: 'G-N5L846TP4Z',
  );
}
